### ISSUE TITLE
Two questions about your project

### ISSUE THREAD

**Issue by rutgersmit** [optimalprimate/coffee-pid#1]
Hi,

I stumbled upon your nice project wjile researching possibilities to add a MQTT driven PID to my Rancilio.
Nice project, exactly what I was looking for: no over-engineered featurecreeped stuf.

When I look at the pictures on your blog I see a switch. Do you use it? It's not in the code, right?
Second, dou you have detailed photo's of the wiring? You state that you can switch between PID mode and the built in thermostat mode, and I'm uncertain how the wiring would support that.

Rutger

**Comment by optimalprimate** [comment]
Hi!

Thanks for your interest!

I did add a switch initially, but I had some issue with debouncing it, so in the end left it out of the code - but would like to come back to it one day - couldn't decide if it would be to turn the system on or to switch between PID and manual control.

I have added a wiring diagram here: https://github.com/optimalprimate/coffee-pid/blob/main/coffee_wiring_bb.png

I don't have the wiring to use the Silvia's original thermostat, that's completely unplugged. Probably my miscommunication, but the switching is between PID mode and just using the ESP8266 as a basic thermostat - i.e. you set a point and the heater is on or off if it is below or above this point respectively.

Hope this helps!
Lucien
